app:
  build: ./nginx
  ports:
    - "5080:80"
    - "5022:22"
    - "50443:443"
  links:
    - db
  volumes_from:
    - appdata
  #environment:
  #  - VIRTUAL_HOST=web.apdev.local

appdata:
  image: tianon/true
  volumes:
    - ./web/:/srv/www/web

db:
  build: ./mysql
  ports:
    - "3306:3306"
  volumes_from:
    - dbdata
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=dev
    - MYSQL_USER=root
    - MYSQL_PASSWORD=root

dbdata:
  image: tianon/true
  volumes:
    - /var/lib/mysql
