FROM mysql:5.6

MAINTAINER Ngo Van Thang <thangnvbkhn@gmail.com>

# Set TERM env to avoid mysql client error message "TERM environment variable not set" when running from inside the container
ENV TERM xterm

EXPOSE 3306